feat: Add filter modal for mobile, move reviews component, and fix desktop filter bug on product list
carlos18bp/candle_project pull request #34
Opened 2024-06-29 01:22 UTC by gustavop-dev

### Description
This pull request includes the following changes:
- **Add filter modal for the product list on mobile devices:** Implemented a modal for filtering products on mobile, enhancing the user experience on smaller screens.
- **Move reviews component in product detail view:** The reviews component has been repositioned to improve layout and readability.
- **Fix bug in desktop version filters:** Resolved an issue affecting the filters on the product list for desktop users.

### Changes
- Implemented a modal with filter options for mobile devices.
- Repositioned the reviews component in the product detail view.
- Fixed a bug causing filters to behave unexpectedly on the desktop version of the product list.

### How to Test
1. **Mobile Filter Modal:**
    - Navigate to the product list on a mobile device.
    - Open the filter modal and verify that it displays correctly and allows filtering products.

2. **Reviews Component:**
    - Go to a product detail view.
    - Ensure the reviews component is now correctly positioned and functions as expected.

3. **Desktop Filters Bug Fix:**
    - Visit the product list on a desktop device.
    - Test the filters to ensure they are working correctly without any issues.

### Additional Notes
- Make sure to test on both mobile and desktop to verify the changes.
- Check for any edge cases that might affect the filter functionality.

2024-07-14 16:09 UTC, carlos18bp requested changes

2024-07-14 16:09 UTC, carlos18bp commented on frontend/src/components/product/ModalFilters.vue
> +                                :currentLanguage="currentLanguage"></CategoryFilter>
Change to:
```
<CategoryFilter v-if="currentLanguage === 'en'" 
   :categories="categories"
   :currentLanguage="currentLanguage">
</CategoryFilter>
```

2024-07-14 16:09 UTC, carlos18bp commented on frontend/src/views/product/Detail.vue
> +                <h2 class="font-regular text-2xl text-gray_p tracking-widest">{{ $t('trending') }}</h2>
Change to:
```
<h2 class="font-regular text-2xl text-gray_p tracking-widest">
   {{ $t('trending') }}
</h2>
```

2024-07-14 16:09 UTC, carlos18bp commented on frontend/src/views/product/Detail.vue
> +                <p class="font-medium text-2xl xl:text-4xl text-black_p mt-12 tracking-wider">{{ $t('text') }}</p>
Change to:
```
<p class="font-medium text-2xl xl:text-4xl text-black_p mt-12 tracking-wider">
   {{ $t('text') }}
</p>
```

2024-07-14 16:09 UTC, carlos18bp commented on frontend/src/views/product/List.vue
> +                            <h1 @click="showModalFilters = true" class="flex items-center gap-2 text-xl font-bold tracking-tight text-gray-900 cursor-pointer test-filter_title">
Change to:
```
 <h1 @click="showModalFilters = true" 
   class="flex items-center gap-2 text-xl font-bold tracking-tight text-gray-900 cursor-pointer test-filter_title">
```

2024-07-17 18:50 UTC, gustavop-dev commented on frontend/src/views/product/List.vue
> +                            <h1 @click="showModalFilters = true" class="flex items-center gap-2 text-xl font-bold tracking-tight text-gray-900 cursor-pointer test-filter_title">
Done!, You can preview the changes in candle-g-21-1

2024-07-17 18:50 UTC, gustavop-dev commented on frontend/src/views/product/Detail.vue
> +                <p class="font-medium text-2xl xl:text-4xl text-black_p mt-12 tracking-wider">{{ $t('text') }}</p>
Done!, You can preview the changes in candle-g-21-1

2024-07-17 18:50 UTC, gustavop-dev commented on frontend/src/views/product/Detail.vue
> +                <h2 class="font-regular text-2xl text-gray_p tracking-widest">{{ $t('trending') }}</h2>
Done!, You can preview the changes in candle-g-21-1

2024-07-17 18:50 UTC, gustavop-dev commented on frontend/src/components/product/ModalFilters.vue
> +                                :currentLanguage="currentLanguage"></CategoryFilter>
Done!, You can preview the changes in candle-g-21-1

2024-07-19 14:20 UTC, carlos18bp approved these changes

2024-07-19 14:20 UTC, carlos18bp commented on frontend/src/components/product/CategoryFilter.vue
> +            <SubCategoryFilter v-if="currentLanguage === 'en'" :subCategories="category.subCategories" />
Change to:
```
<SubCategoryFilter v-if="currentLanguage === 'en'" 
   :subCategories="category.subCategories" />
```

2024-07-19 14:20 UTC, carlos18bp commented on frontend/src/components/product/CategoryFilter.vue
> +            <SubCategoryFilter v-if="currentLanguage === 'es'" :subCategories="category.subCategorias" />
Change to:
```
<SubCategoryFilter v-if="currentLanguage === 'es'" 
   :subCategories="category.subCategorias" />
```

2024-07-19 14:20 UTC, carlos18bp commented on frontend/src/views/product/Checkout.vue
> +                    <button class="px-4 py-2 bg-primary_p rounded-lg text-white text-xl font-regular">{{ $t('pay_now') }}</button>
Change to:
```
<button class="px-4 py-2 bg-primary_p rounded-lg text-white text-xl font-regular">
   {{ $t('pay_now') }}
</button>
```

2024-07-24 11:17 UTC, gustavop-dev commented on frontend/src/components/product/CategoryFilter.vue
> +            <SubCategoryFilter v-if="currentLanguage === 'en'" :subCategories="category.subCategories" />
Done!

2024-07-24 11:17 UTC, gustavop-dev commented on frontend/src/components/product/CategoryFilter.vue
> +            <SubCategoryFilter v-if="currentLanguage === 'es'" :subCategories="category.subCategorias" />
Done!

2024-07-24 11:17 UTC, gustavop-dev commented on frontend/src/views/product/Checkout.vue
> +                    <button class="px-4 py-2 bg-primary_p rounded-lg text-white text-xl font-regular">{{ $t('pay_now') }}</button>
Done!

2024-07-24 11:22 UTC, merged