Integration of Square Payment Gateway
carlos18bp/candle_project pull request #35
Opened 2024-07-05 19:23 UTC by gustavop-dev

# Integration of Square Payment Gateway

## Description

This PR implements the integration of the Square payment gateway into our system using Django for the backend and Vue.js for the frontend. The integration allows users to make payments directly through our application using Square's Payments API.

## Changes Made

### Frontend (Vue.js)

**1. Payment Form Component:**
   - Created a new `PaymentForm.vue` component to handle the credit card tokenization using Square's SDK.
   - Added logic to manage and send the payment token to the backend.

**2. Create Sale Function:**
   - Updated the `createSale` function in the Vue store to send the necessary data to the backend and handle the response appropriately.
   - Example usage of `createSale`:
     ```javascript
     async createSale(form) {
       try {
         const response = await create_request('create-sale/', {
           email: form.email,
           address: form.address,
           city: form.city,
           state: form.state,
           postal_code: form.postalCode,
           sold_products: form.soldProducts,
           total: form.total,
           sourceId: form.sourceId,
           locationId: form.locationId,
           idempotencyKey: Math.random().toString(36).substring(2),
         });

         return response.status;
       } catch (error) {
         console.error('Error creating sale:', error);
         throw error;
       }
     }
     ```

**3. Checkout View:**
   - Modified the `handleSubmit` function to handle the entire payment process, including tokenization, sale creation, and response handling.
   - Example:
     ```javascript
     const handleSubmit = async () => {
       try {
         const token = await paymentFormRef.value.handlePaymentMethodSubmission();
         form.sourceId = token;
         form.soldProducts = extractProductInfo(cartProducts.value);
         const status = await productStore.createSale(form);

         if (status === 201) {
           Swal.fire({
             title: "The payment has been processed successfully",
             icon: "success"
           });

           localStorage.removeItem("cartProducts");
           productStore.cartProducts = [];
           router.push({ name: "home" });
         } else {
           Swal.fire({
             title: "Payment failed",
             text: "An error occurred while processing your payment",
             icon: "error"
           });
         }
       } catch (error) {
         console.error('Error during payment processing:', error);
         Swal.fire({
           title: "Payment failed",
           text: error.message,
           icon: "error"
         });
       }
     };
     ```

### Backend (Django)

**1. Create Sale Endpoint:**
   - Created a new API endpoint in Django to handle the payment processing and sale creation.
   - Configured the Square client and integrated the payment processing logic.
   - Example:
     ```python
     from rest_framework.decorators import api_view
     from rest_framework.response import Response
     from rest_framework import status
     from square.client import Client
     from candle_app.serializers import SaleSerializer
     import uuid

     @api_view(['POST'])
     def create_sale(request):
         if request.method == 'POST':
             data = request.data
             source_id = data.get('sourceId')
             location_id = data.get('locationId')
             idempotency_key = data.get('idempotencyKey')
             total = data.get('total')

             if not total:
                 return Response({"error": "Total amount is required"}, status=status.HTTP_400_BAD_REQUEST)

             amount_in_cents = int(float(total) * 100)

             client = Client(
                 access_token='YOUR_SQUARE_ACCESS_TOKEN',
                 environment='sandbox'
             )
             payments_api = client.payments

             body = {
                 "source_id": source_id,
                 "location_id": location_id,
                 "idempotency_key": idempotency_key,
                 "amount_money": {
                     "amount": amount_in_cents,
                     "currency": "USD"
                 }
             }

             try:
                 result = payments_api.create_payment(body)
                 if result.is_success():
                     serializer = SaleSerializer(data=data)
                     if serializer.is_valid():
                         serializer.save()
                         return Response(serializer.data, status=status.HTTP_201_CREATED)
                     return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
                 else:
                     return Response(result.errors, status=status.HTTP_400_BAD_REQUEST)
             except Exception as e:
                 return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
     ```

## How to Test

**1. Frontend:**
   - Navigate to the checkout page and fill out the payment form.
   - Submit the form and verify that the payment is processed and a success message is displayed.
   - Check that the cart is cleared and you are redirected to the home page.

**2. Backend:**
   - Verify that the `create-sale` endpoint is receiving the correct data and processing payments successfully.
   - Ensure that sales are created in the database and all relevant data is stored correctly.

## Notes

- Make sure to replace `YOUR_SQUARE_ACCESS_TOKEN` with your actual Square access token.
- This integration is currently set up for the Square sandbox environment. Change the environment to 'production' when ready to go live.
- For 'production' It's neccesary change:

- `YOUR_SQUARE_ACCESS_TOKEN` 
- `YOUR_SQUARE_APPLICATION_ID` 
- `YOUR_SQUARE_LOCATION_ID` 
- `<script src="https://sandbox.web.squarecdn.com/v1/square.js"></script>` to `<script src="https://web.squarecdn.com/v1/square.js"></script>`

2024-07-14 16:19 UTC, carlos18bp requested changes

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/alerts/AlertShoppingCart.vue
> +            <a @click="shoppingCartToggle = true" class="cursor-pointer underline test-addShoppingCart-seeCart">{{ $t('addShoppingCart').seeCart }}</a>
Change to:
```
<a @click="shoppingCartToggle = true" 
   class="cursor-pointer underline test-addShoppingCart-seeCart">
   {{ $t('addShoppingCart').seeCart }}
</a>
```

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/alerts/AlertShoppingCart.vue
> +        <ShoppingCart :visible="shoppingCartToggle" @update:visible="shoppingCartToggle = $event"></ShoppingCart>
Change to:
```
<ShoppingCart :visible="shoppingCartToggle" 
   @update:visible="shoppingCartToggle = $event">
</ShoppingCart>
```

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/animations/Loading.vue
> +    <Vue3Lottie :animationData="animationData" :height="height" :width="width" :loop="loop" :autoplay="autoplay" />
Change to:
```
 <Vue3Lottie :animationData="animationData" 
   :height="height" 
   :width="width" 
   :loop="loop" 
   :autoplay="autoplay" />
```

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/animations/ScreenLoading.vue
> +            <Vue3Lottie :animationData="animationData" :height="600" :width="600" :loop="true" :autoplay="true"></Vue3Lottie>
Change to:
```
<Vue3Lottie :animationData="animationData" 
   :height="600" 
   :width="600" 
   :loop="true" 
   :autoplay="true">
</Vue3Lottie>
```

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/payments/PaymentForm.vue
> +        <LoadingAnimation :height="300" :width="300" :loop="true" :autoplay="true"></LoadingAnimation>
Change to:
```
<LoadingAnimation :height="300" 
   :width="300" 
   :loop="true" 
   :autoplay="true">
</LoadingAnimation>
```

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/payments/PaymentForm.vue
> +    }
Add one tab here

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/payments/PaymentForm.vue
> +    } catch (e) {
Change `e` to `error`

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/payments/PaymentForm.vue
> +    }
Add one tab here

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/payments/PaymentForm.vue
> +    handlePaymentMethodSubmission,
Add one tab here

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/components/payments/PaymentForm.vue
> +    loading.value = false;
Add one tab here

2024-07-14 16:19 UTC, carlos18bp commented on frontend/src/views/product/Detail.vue
> +        <AlertShoppingCart :visible="showAlertShoppingCart" @update:visible="showAlertShoppingCart = $event"></AlertShoppingCart>
Change to:
```
<AlertShoppingCart :visible="showAlertShoppingCart" 
   @update:visible="showAlertShoppingCart = $event">
</AlertShoppingCart>
```

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/alerts/AlertShoppingCart.vue
> +            <a @click="shoppingCartToggle = true" class="cursor-pointer underline test-addShoppingCart-seeCart">{{ $t('addShoppingCart').seeCart }}</a>
Done!

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/alerts/AlertShoppingCart.vue
> +        <ShoppingCart :visible="shoppingCartToggle" @update:visible="shoppingCartToggle = $event"></ShoppingCart>
Done!

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/animations/Loading.vue
> +    <Vue3Lottie :animationData="animationData" :height="height" :width="width" :loop="loop" :autoplay="autoplay" />
Done!

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/animations/ScreenLoading.vue
> +            <Vue3Lottie :animationData="animationData" :height="600" :width="600" :loop="true" :autoplay="true"></Vue3Lottie>
Done!

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/payments/PaymentForm.vue
> +        <LoadingAnimation :height="300" :width="300" :loop="true" :autoplay="true"></LoadingAnimation>
Done!

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/payments/PaymentForm.vue
> +    }
Done!

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/payments/PaymentForm.vue
> +    } catch (e) {
Done!

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/payments/PaymentForm.vue
> +    }
Done!

2024-07-17 18:44 UTC, gustavop-dev commented on frontend/src/components/payments/PaymentForm.vue
> +    handlePaymentMethodSubmission,
Done!

2024-07-17 18:45 UTC, gustavop-dev commented on frontend/src/components/payments/PaymentForm.vue
> +    loading.value = false;
Done!

2024-07-17 18:45 UTC, gustavop-dev commented on frontend/src/views/product/Detail.vue
> +        <AlertShoppingCart :visible="showAlertShoppingCart" @update:visible="showAlertShoppingCart = $event"></AlertShoppingCart>
Done!

2024-07-17 19:27 UTC, carlos18bp approved these changes

2024-07-17 19:27 UTC, carlos18bp commented on frontend/src/components/alerts/AlertShoppingCart.vue
> +            <a @click="shoppingCartToggle = true" class="cursor-pointer underline test-addShoppingCart-seeCart">
Change to: 
```
<a @click="shoppingCartToggle = true" 
   class="cursor-pointer underline test-addShoppingCart-seeCart">
```

2024-07-17 19:53 UTC, gustavop-dev commented on frontend/src/components/alerts/AlertShoppingCart.vue
> +            <a @click="shoppingCartToggle = true" class="cursor-pointer underline test-addShoppingCart-seeCart">
Done!

2024-07-17 19:53 UTC, merged